### ISSUE TITLE
Add detection details to technologies

### ISSUE THREAD

**Issue by nukerr** [AliasIO/wappalyzer.com#12]
I think it would be nice to have the detection code on the technology page:

Something like that ([AlpineJS](https://www.wappalyzer.com/technologies/javascript-frameworks/alpine-js/) for example):  
JS: 
`Alpine.version`
Script:
`/alpine(?:\\.min)?\\.js`

**Comment by AliasIO** [comment]
Thanks for the suggestion. I like the idea but don't think we'll add that as the pages are largely intended for a non-technical audience, I'm not sure how many people would find it useful.
